# Generated by Django 3.2.12 on 2022-03-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='author',
        ),
        migrations.AddField(
            model_name='todo',
            name='user',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='git_name',
            field=models.CharField(max_length=64),
        ),
    ]
