# Generated by Django 3.2.12 on 2022-03-20 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.user'),
        ),
    ]
